name: Make NDK (Linux)
run-name: Make NDK-r${{inputs.version}}${{inputs.revision}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: "30"
        required: true
        type: string
      revision:
        description: "NDK Release revision:"
        required: false
        type: string
      only:
        description: "Only these targets (JSON array), default all"
        required: false
        type: string

permissions:
  contents: write
  packages: read

jobs:
  make:
    uses: ./.github/workflows/make-ndk.yml
    secrets: inherit
    with:
      platform: linux
      version: ${{ inputs.version }}
      revision: ${{ inputs.revision }}
      only: ${{ inputs.only }}
      # loongarch32-linux-gnu, loongarch32-linux-gnusf
      targets: >-
        ["aarch64-linux-musl"]
